### PR TITLE
remove redundant nav title from desktop, place next to buttons on mobile

### PR DESCRIPTION
**Pull request by Rich-Harris**

### CODE REVIEW

**Comment by Rich-Harris** [comment]
It doesn't make sense to have the subtitle on desktop when the link is highlighted, especially when it causes layout shift:

image

It also doesn't make sense to have the 'Docs' subtitle be part of a link that takes you home. This PR moves it to the right hand side, where it's also more obviously connected to the menu button

image

**Review by PuruVJ — COMMENTED** [review]
Lfg! Only thing is, if it's next to the button, maybe it gives off a feeling that it is a link as well?

Also, on another unrelated note, should we have a search icon before the menu icon? Seems that to search, you have to do three click to reach it, with the icon it will be just one

**Comment by Rich-Harris** [comment]
Yeah, a search icon makes sense, though in that case we'd want to remove it from the menu. We could probably make 'Docs' look less link-like by tweaking the styles (i.e. graying it a bit)

**Comment by Rich-Harris** [comment]
image

**Comment by benmccann** [comment]
Makes sense to remove it from desktop. "Docs" looks a bit out-of-place in the updated mobile design. It's not really clear what it's connected to or that it's referring to the current page. I think the original mobile design worked better in that regard

**Comment by Rich-Harris** [comment]
It just didn't make sense that the word 'docs' was part of a link that went to `/`. Personally I'd be in favour of removing it altogether, I think it's completely unnecessary, and will eventually cause us layout headaches

**Comment by benmccann** [comment]
Another option would be to unlink the logo on mobile. It's not often you need to navigate back to the homepage and we can have a homepage link in the menu

**Comment by PuruVJ** [comment]
I agree with ben, previous design specified more. Like "hey, you're on svelte site, and on the docs page".

However, we can steal some things from your design. For example, the text can be smaller and grey, and as ben stated, the text can not be a link, while the Svelte logo stays a link. I think logo taking you to home page is too widespread of a pattern to not have

**Pull request merged**
