### PR TITLE
Make sure there are newlines between lines when copying code snippets

### PR DESCRIPTION
**Pull request by mimbrown**
I noticed while using the sveltekit site that copying the codeblocks didn't include a lot of necessary newline characters. This is a simple fix that seems to fix the problem I was facing, but it might need to be more sophisticated.

### CODE REVIEW

**Comment by PuruVJ** [comment]
Can you specify the exact code snippets which give the problem? I tried on my end and this fix just adds 2 lines more, so there's maybe a more granular solution

**Comment by mimbrown** [comment]
Sure, try copying the first snippet (and probably the others too) on the [service worker sveltekit page](https://kit.svelte.dev/docs/service-workers). Could be a problem with when the HTML is generated instead of when it's traversed, I don't know.

**Comment by mimbrown** [comment]
I get:

```js
if ('serviceWorker' in navigator) {	addEventListener('load', function () {		navigator.serviceWorker.register('./path/to/service-worker.js');	});}
```

**Comment by dummdidumm** [comment]
From a quick test it seems that Svelte files are fine, but JS files are mostly broken.

**Comment by benmccann** [comment]
I just tested that code block on the new site and it appears to be working now, so I'll go ahead and close this

If there are any further changes needed, we've merged svelte.dev and kit.svelte.dev together into a single site, so the site-kit now lives here: https://github.com/sveltejs/svelte.dev/tree/main/packages/site-kit

**Pull request closed without merging**
