### PR TITLE
Monochrome terminal chrome

### PR DESCRIPTION
**Pull request by benmccann**
### current version on kit.svelte.dev

Screenshot from 2023-06-05 09-07-58

### updated version for new svelte.dev site

Screenshot from 2023-06-05 09-07-27

### CODE REVIEW

**Comment by PuruVJ** [comment]
How does it look in dark mode? Can you post screenshot?

**Comment by vedam** [comment]
I would recommend not making it this dark.
I think a dark gray should be enough and a bit friendlier.

**Comment by benmccann** [comment]
Here's one that's a hint lighter so that it matches the text color:

Screenshot from 2023-06-05 09-33-40

And a screenshot of what it looks like in dark mode:

Screenshot from 2023-06-05 09-36-24

**Comment by Rich-Harris** [comment]
I don't think the title bar should be darker than the window itself. Here's what the actual MacOS terminal looks like in light and dark modes:

image

image


Perhaps something more like this? It's `#888` on `#444`, which I think works fine in both light and dark modes:

image

**Comment by benmccann** [comment]
The current `version-4` branch uses a different color for the background, which makes `#444` not really work because it blends into the background.

Screenshot from 2023-06-07 22-02-21

I changed it to `#999` on `#666` instead

Screenshot from 2023-06-07 22-07-39

**Comment by Rich-Harris** [comment]
What about darkening the background instead? It's a bit wishy washy anyway

**Comment by benmccann** [comment]
I can't really darken the background because the sections above and below are darker and then it blends in too much with them

Maybe if we merge this as it is it will be easier to iterate on because then folks can see it in the deploy preview for the `version-4` site. If we can at least get in the ballpark it will give a sense of what we're going for and then we can tweak things in followups

**Pull request merged**
