### PR TITLE
GIT service as a settable property

### PR DESCRIPTION
**Pull request by vorcigernix**
To allow use this component in gitlab environment.

### CODE REVIEW

**Comment by antony** [comment]
@vorcigernix would this also work for - for example, bitbucket URLs?

How uniform is the full path to repositories?

**Comment by vorcigernix** [comment]
I tried to google how different is bitbucket and honestly: I don't know. This should fix the issue at least for all services which follow /{owner}/{project} scheme, making this work universally would require some experience with other services I don't have (if it is possible at all).

**Comment by antony** [comment]
I suppose what I'd suggest here then is setting this as individual properties / an object so that we don't need to go and fix all references if a non-conforming service is added. 

You could specify org, repo, and service, and the url could be built based on what we do know of the format.

Results in a smoother upgrade path (no breaking changes) as more services are added.

**Comment by Rich-Harris** [comment]
Maybe it should be a function rather than a set of properties?

**Pull request closed without merging**
